### ISSUE TITLE
Account abstraction

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#1]

**Comment by sam-tokendistro** [comment]
Given the limited amount of wallets that support Stark keys, I think it would be great to have an `eth_public_key` owner as well on the [Account contract](https://github.com/OpenZeppelin/cairo-contracts/blob/main/contracts/Account.cairo), which can be used to change the `stark_public_key` once ETH signatures are supported.

**Comment by sam-tokendistro** [comment]
The idea is that when you initialize you can just use a `eth_public_key` and later set or change the `stark_public_key`.

**Comment by martriay** [comment]
Thanks for the input! I'm in talks with different wallets and I don't think there's consensus on what set of keys to use yet: some of them prefer going with stark keys directly due to performance, while others prefer to minimize integration requirements (i.e., reuse either private keys or at least mnemonics).

I'd like to stick to stark keys for the time being, at least for simplicity. That being said, there's already an `L1_address` storage variable, but the idea is to have an L1 exit mechanism rather than approving transactions.
