### ISSUE TITLE
Simplify hook impl in erc20_votes mock

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/cairo-contracts#1015]
We can simplify the hooks implementation by passing in the mock's `ContractState` instead of the component's state. See the examples in [Extending Contracts with Hooks](https://medium.com/@fleming-andrew/extending-cairo-contracts-with-hooks-c3ca21d1d6b8)

**Comment by ggonzalez94** [comment]
Should be closed once we merge #1114

**Comment by ggonzalez94** [comment]
Closing now that #1114 was merged and the votes mocks were refactored
