### ISSUE TITLE
ERC2981 implementation in Cairo

### ISSUE THREAD

**Issue by ptisserand** [OpenZeppelin/cairo-contracts#1041]
**🧐 Motivation**
[ERC2981](https://eips.ethereum.org/EIPS/eip-2981) is a standardized way to retrieve royalty payment information for non-fungible tokens (NFTs) to enable universal support for royalty payments across all NFT marketplaces and ecosystem participants.

**📝 Details**
There are many marketplaces for NFTs with multiple unique royalty payment implementations that are not easily compatible or usable by other marketplaces. Just like the early days of ERC-20 tokens, NFT marketplace smart contracts are varied by ecosystem and not standardized. ERC2981 enables all marketplaces to retrieve royalty payment information for a given NFT. This enables accurate royalty payments regardless of which marketplace the NFT is sold or re-sold at.

Here is a proposal for ERC2981 interface:
```cairo
const IERC2981_ID: felt252 = 0x2d3414e45a8700c29f119a54b9f11dca0e29e06ddcb214018fc37340e165ed6;

#[starknet::interface]
pub trait IERC2981<TState> {
    fn royalty_info(self: @TState, token_id: u256, sale_price: u256) -> (ContractAddress, u256);
}
```

Please note that I have wrote [a first implementation](https://github.com/ArkProjectNFTs/ark-project/tree/acda11aa6f25cf18146993148cff6f6079af10da/contracts/ark_oz) for the [Ark Project](https://www.arkproject.dev/), I can adapt for addition to OZ Cairo library.

**Comment by ericnordelo** [comment]
Added in #1091
