### ISSUE TITLE
Impl AccessControl is not pub

### ISSUE THREAD

**Issue by NirLevi-starkware** [OpenZeppelin/cairo-contracts#1045]
https://github.com/OpenZeppelin/cairo-contracts/blob/4f4e2e48bd86d99c3ee5ee405140bf1681529a2e/src/access/accesscontrol/accesscontrol.cairo#L71

please fix, ty :)

**Comment by ericnordelo** [comment]
Hey @NirLevi-starkware. That implementation is not public on purpose since the one that should be used is the `AccessControlImpl` which is public. If you need it for a specific use case we may not be aware of, please feel free to reopen the issue and provide more context.
