### ISSUE TITLE
can't compile on macos

### ISSUE THREAD

**Issue by oleksiivinogradov** [OpenZeppelin/cairo-contracts#1068]
scarb build
    Updating git repository https://github.com/openzeppelin/cairo-contracts
error: Version solving failed:
- openzeppelin v0.15.0-rc.0 (git+https://github.com/OpenZeppelin/cairo-contracts.git?tag=v0.15.0-rc.0#6869190bbc3eef90f49651a42e0b44dcc4bec842) cannot use starknet v2.7.0-rc.3 (std), because openzeppelin requires starknet ^2.6.4

scarb --version
scarb 2.7.0-rc.4 (88bf93564 2024-07-19)
cairo: 2.7.0-rc.3 (https://crates.io/crates/cairo-lang-compiler/2.7.0-rc.3)
sierra: 1.6.0

**📝 Details**

I can't compile empty project:

[package]
name = "motodex_starknet_contracts_new"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.7.0-rc.3"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.0-rc.0" }

[dev-dependencies]
cairo_test = "2.7.0-rc.3"

**🔢 Code to reproduce bug**

**Comment by ericnordelo** [comment]
Hey @oleksiivinogradov, that release candidate works with 2.6.4 (cairo version), and not with 2.7. We haven't release a version supporting 2.7 yet, but if you want to experiment with it, even while it is not recommended for production releases, you can use the main branch.

**Comment by oleksiivinogradov** [comment]
> Hey @oleksiivinogradov, that release candidate works with 2.6.4 (cairo version), and not with 2.7. We haven't release a version supporting 2.7 yet, but if you want to experiment with it, even while it is not recommended for production releases, you can use the main branch.

If i take look current release, I saw another info:

**Comment by ericnordelo** [comment]
The release candidate uses 2.6.4 as you can see [here](https://github.com/OpenZeppelin/cairo-contracts/blob/v0.15.0-rc.0/Scarb.toml).

What you are seeing there is probably the main branch, which is not the release commit (tag).

**Comment by oleksiivinogradov** [comment]
I must use main branch, bcs need 2.7.0 for my code
I solve it by copy code, but maybe better to check main branch about
