### ISSUE TITLE
ERC721 Transfer token no token id

### ISSUE THREAD

**Issue by ltdai010** [OpenZeppelin/cairo-contracts#107]
ERC721 contract transfer function is probably wrong

**📝 Details**

Transfer function of ERC721 contract should change not just the balance but the owner of the token as well.
What I see is just increase receiver balance and decrease sender balance like ERC20

**🔢 Code to reproduce bug**

```
func _transfer{
        syscall_ptr : felt*, 
        pedersen_ptr : HashBuiltin*,
        range_check_ptr
    }(sender: felt, recipient: felt, amount: felt):
    # validate sender has enough funds
    let (sender_balance) = balances.read(user=sender)
    assert_nn_le(amount, sender_balance)

    # substract from sender
    balances.write(sender, sender_balance - amount)

    # add to recipient
    let (res) = balances.read(user=recipient)
    balances.write(recipient, res + amount)
    return ()
end
```
Take a look, it's probably wrong.

**Comment by RedBeardEth** [comment]
Try working off the PR at #108 

It adds to the above function:

`    ERC721_owners.write(token_id.low, token_id.high, to)
`

It's working fairly smoothly for me so far

**Comment by martriay** [comment]
Indeed, that implementation is severely incomplete, it's a half baked draft. The actual implementation is coming at #108.
