### ISSUE TITLE
Implementation of SNIP-9

### ISSUE THREAD

**Issue by PhilippeR26** [OpenZeppelin/cairo-contracts#1110]
**🧐 Motivation**
SNIP-9 Outside Execution (https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-9.md) is implemented in ArgentX & Braavos account contracts.

**📝 Details**
Do you plan to implement soon this very useful feature?

**Comment by ericnordelo** [comment]
Hey @PhilippeR26, this is something we want to include for sure. Thanks for opening the issue.

**Comment by PhilippeR26** [comment]
I have implemented SNIP-9 in Starknet.js. So, if you have questions about SNIP-9, don't hesitate to contact me.
