### ISSUE TITLE
Failed transactions can't be reprocessed due to current_nonce logic

### ISSUE THREAD

**Issue by hubsmoke** [OpenZeppelin/cairo-contracts#112]
Problem: Buggy signing code or a malicious actor can prevent an Account contract from being used by submitting a StarkNet transaction that fails due to invalid signature. Because StarkNet Alpha v4 does not allow resubmitting/updating a previously submitted transaction hash, a failed contract invocation due to invalid signature can guarantee future failures, even for future properly signed calls with the same transaction hash (same nonce + parameters).

Potential Solutions: StarkNet should allow reprocessing of same transaction hash or the Account contract should support nonces > current_nonce

Steps to reproduce:

1) Deploy Account contract
2) submit an execute transaction invoking a specific external contract, such as the Counter contract (https://github.com/fracek/starknet-react-example) with an increment of 1, but with an invalid signature
3) The transaction fails due to invalid signature
4) Reinvoke the same call with the same nonce + arguments, but include a valid signature
5) The transaction will not be reprocessed on StarkNet Alpha v4

Workaround: After the failed invocation with the bad signature, Invoke a different contract with a correct signature, which forces the nonce to increment, and you can make a successful invocation with the newly updated nonce

Note: It is unclear to me if the problem can occur with a correct signature. For example, if Alice makes an invocation that fails for some other reason, like an assertion failing due to a contract state. Then say the state on the target contract is updated by Bob, which should result in a success should Alice attempt to make the same call again. Alice's invocation could fail because StarkNet Alpha v4 will not reprocess the transaction due to having the same transaction hash.

Background: https://www.cairo-lang.org/docs/hello_starknet/user_auth.html#what-if-we-have-an-invalid-signature

**Comment by martriay** [comment]
Thanks for this detailed issue. Given this is a wider StarkNet issue, I'm closing this in favor of discussing on the [StarkNet Shamans forum](https://community.starknet.io/t/duplicate-transaction-hash-questions/254/2).
