### ISSUE TITLE
Normalize `IDeclarer` and `IDeployable` suffixes

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/cairo-contracts#1147]
The account package offers a few optional interfaces which include `IDeclarer` and `IDeployable`. It seems odd that they have different suffixes. I propose that we normalize them with either:

`IDeclarer` and `IDeployer`
or
`IDeclarable` and `IDeployable`

**Comment by ericnordelo** [comment]
The Account declares or gets deployed with those interfaces, it doesn't get declared or deploys from those functions. Using the same suffix sounds weird to me because of this.

**Comment by andrew-fleming** [comment]
Good point 👍
