### ISSUE TITLE
Reorganize contract directory structure

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#115]
Base token contracts, their interfaces and presets are all thrown into the same folder today. We should think of a better way to organize files, with a focus on discoverability and ease of import paths declaration.

**Comment by ponderingdemocritus** [comment]
IMO - Tokens should be in their own dirs.

ERC20
ERC721
ERC1155

Same pattern as .sol files

Etc

**Comment by andrew-fleming** [comment]
@ponderingdemocritus I agree with separating the directories by tokens as you mentioned above to follow the OZ Solidity pattern. To further organize, I'm thinking we continue following the original implementation and include `extensions` and `presets`. To illustrate:

```
contracts
    └──Token
          ├── extensions
                └──Extension_Token.cairo
          ├── presets
                └──Preset_Token.cairo
          ├── Token_base.cairo
          ├── Token.cairo
          └── IToken.cairo
```

Finally, I think it makes sense to reorganize the tests to follow suit—at least separating them by token.

I'm going to build on this and submit a new PR (separate from #118 ) to compartmentalize this feature.

**Comment by martriay** [comment]
Note that `Token.cairo` is also a preset. Are `extensions/` files always base contracts? Because if presets are always frontend contracts and the extensions will also have presets, I wonder if it makes sense to group by base vs frontend contracts.

**Comment by andrew-fleming** [comment]
`extensions/` files indeed are always base contracts. I was concerned that it might be confusing, but after writing a mockup, I think that idea works better. In which case, adding `interfaces/` seems appropriate. Here's a mock structure:
```
contracts
    └──Token
          ├── base_contracts
                ├── Token_base.cairo
                └── Token_Extension_base.cairo
          ├── frontend_contracts
                ├── Token.cairo
                └── Token_Preset.cairo
          └──interfaces
                ├── IToken.cairo
                └── IToken_Preset.cairo
```

**Comment by martriay** [comment]
Now that we're seeing a more clear distinction between _libraries_ and _contracts_ (formerly known as _base contracts_  and _frontend contracs_ respectively), I think the next step is to think this issue from two UX-first perspectives:

1. how easy/happy is to import modules
2. how feature/contract discoverability looks like for users

Let's think for a moment about how imports look like:

1. Library import: `from contracts.token.ERC20.libraries.ERC20_base import (...`
2. Interface import: `from contracts.token.ERC721.interfaces.IERC721 import IERC721`

The first one definitely doesn't look good. What about something like:

```
// libraries
from contracts.token.ERC20.library import (...)
from contracts.token.ERC721.library import (...)
from contracts.token.ERC721_Enumerable.library import (...)

// interfaces
from contracts.token.ERC20.interface import IERC20
from contracts.token.ERC721.interface import IERC721
from contracts.token.ERC721_Enumerable.interface import IERC721_Enumerable
```

What I like about this proposal is that all ERC20 or ERC721 modules are kept together in the directory structure, if we don't care about that (we should), we could go with something like:

```
// libraries
from contracts.token.library.ERC20 import (...)
from contracts.token.library.ERC721 import (...)
from contracts.token.library.ERC721_Enumerable import (...)

// interfaces
from contracts.token.interfaces.ERC20 import IERC20
from contracts.token.interfaces.ERC721 import IERC721
from contracts.token.interfaces.ERC721_Enumerable import IERC721_Enumerable
```

This other one reads a bit better, but at the same time I think it's harder to miss where are you importing from (the interface/library part of the path is easy to ignore) as well as separating files throughout the dir structure. More so if we move the interface/library directory up one level so that `token` ends up within it.

What do the rest think about this?

**Comment by georgercarder** [comment]
The last proposed structure has nicer looking import file paths, but the second to last proposed structure would look nicer in the repo and keep corresponding libraries and interfaces more closely accessible from an fs point of view. 
My vote is for the second to last proposal.

**Comment by frangio** [comment]
I like `contracts.token.ERC20.library`. But where do "contracts" fit into this structure?

**Comment by martriay** [comment]
well since they're not meant to be imported, they can just be siblings of the library modules no?

**Comment by fracek** [comment]
I also like `contracts.token.ERC20.library`, but maybe that should be `openzeppelin.token.ERC20.library`. Also not sure about the capitalization of `ERC20` vs `erc20`.

**Comment by frangio** [comment]
+1 to `openzeppelin` and lowercase `erc20` for directories.

Then the contract would be `token/erc20/ERC20.cairo`?

**Comment by martriay** [comment]
> Then the contract would be token/erc20/ERC20.cairo?

yes, but that's preset discovery so not really for importing.
mhh maybe they can be imported considering `@externals` are auto-exported. we should explore that model.
