### ISSUE TITLE
Wizard: ERC721 implementation does not automatically expose SRC5

### ISSUE THREAD

**Issue by credence0x** [OpenZeppelin/cairo-contracts#1251]
This is missing from the wizard when you try to create a template ERC721
    `#[abi(embed_v0)]
    impl SRC5Impl = SRC5Component::SRC5Impl<ContractState>;`
    
  Not including it will cause indexers to misbehave

**Comment by ericnordelo** [comment]
Hey @credence0x. `supports_interface`, the only function in `SRC5Impl`, is part of the `ERC721Mixin` implementation, which is exposed, so that shouldn't be an issue for indexers.

**Comment by credence0x** [comment]
ah i see. thanks
