### ISSUE TITLE
`ERC721_burn` transfers control of token to non(Account)

### ISSUE THREAD

**Issue by georgercarder** [OpenZeppelin/cairo-contracts#145]
The `ERC721_burn` function of the `ERC721_base.cairo` file attempts to clear approvals and delete the owner for a given `tokenId`. This attempt uses the pattern of setting the approval and owner address to be zero. 

In the EVM this workflow fits in with its account model. But in this Startnet environment, functions can actually be invoked with caller the "zero" address when not routed through a contract such as `Account.cairo`.

This means that `ERC721_burn` actually makes the owner this "zero" address and now any user can seize control of this token by making calls not routed through such an `Account.cairo` contract.

I will push a PR promptly that should fix this issue.

**Comment by andrew-fleming** [comment]
If I understand this correctly, I believe we have a check for this. When `transferFrom` is called, it invokes `_transfer` which checks that the owner is not the zero address with `ownerOf`. See [here](https://github.com/OpenZeppelin/cairo-contracts/blob/main/contracts/token/ERC721_base.cairo#L333-L335). Thus, if you try to transfer a burned token (whose owner is `0` after the burn) as the zero address, the tx will still fail

**Comment by georgercarder** [comment]
You are right @andrew-fleming . I did not see that at first.

Indeed, the `_transfer` function calls the `ERC721_ownerOf` function, which itself makes asserts that the returned `owner` is not the zero address.

This should then be resolved as not being an issue. So we know now that as programmed, the `ERC721_burn` function does not have this as a vulnerability.

**Comment by martriay** [comment]
Note that all safety checks are meant to be in the internal functions. The internal functions are considered building blocks of greater functionality, and they're responsible for the maintaining its own invariants, therefore these checks belong to the internal functions :)

**Comment by andrew-fleming** [comment]
@georgercarder I appreciate you looking for vulnerabilities 🙏

**Comment by martriay** [comment]
Just don't find them ok???

**Comment by andrew-fleming** [comment]
What I meant^ :)

**Comment by georgercarder** [comment]
I won't find them.. so long as you don't make them :)
