### ISSUE TITLE
ERC165 interface ids are strings

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/cairo-contracts#147]
It seems to me that we're using short strings as the ERC165 interface ids:

https://github.com/OpenZeppelin/cairo-contracts/blob/87d6d81d0cbbd2b5b7dca5ef5c503d3a8e01ad86/contracts/token/ERC721_base.cairo#L62

My understanding is that `'0x80ac58cd'` is a short string that starts with the characters `0x`, where what we want is the hex bytes `80ac58cd`.

We could write `0x80ac58cd` without quotes, though I think this is a felt with the least significant bits set, and perhaps it should be aligned to the most significant bits?

**Comment by martriay** [comment]
Why should it be aligned to the most significant bits? I think we should leave bitwise representation to the language, and just make sure we're passing the hex (or decimal) number instead of the short string.

**Comment by frangio** [comment]
If you see a felt as a vector of bits it makes sense to me that the significant bits should be at the beginning.

But either way is good.

**Comment by frangio** [comment]
It seems short strings are also aligned to the least significant bits so that choice seems consistent.
