### ISSUE TITLE
ERC721_transferFrom and ERC721_safeTransferFrom allow improper transfer of tokens

### ISSUE THREAD

**Issue by smonicas** [OpenZeppelin/cairo-contracts#148]
Hi,

I work at [Trail of Bits](https://www.trailofbits.com/) and I noticed a critical bug recently introduced in the ERC721 support: an incorrect handling of the zero address in ERC721_transferFrom <link to code>/ ERC721_safeTransferFrom <link to code> allows anyone to steal the tokens. https://github.com/OpenZeppelin/cairo-contracts/blob/87d6d81d0cbbd2b5b7dca5ef5c503d3a8e01ad86/contracts/token/ERC721_base.cairo#L183-L194 https://github.com/OpenZeppelin/cairo-contracts/blob/87d6d81d0cbbd2b5b7dca5ef5c503d3a8e01ad86/contracts/token/ERC721_base.cairo#L196-L213

In cairo, calling a function directly (i.e, without going through an account contract) lead the message’s sender to be [zero](https://starknet.io/docs/hello_starknet/user_auth.html#getting-the-caller-address).

ERC721_getApproved returns the address approved: https://github.com/OpenZeppelin/cairo-contracts/blob/87d6d81d0cbbd2b5b7dca5ef5c503d3a8e01ad86/contracts/token/ERC721_base.cairo#L109-L119
However if no address was approved, this will return the zero address (as storage is initialized to 0).

As a result, anyone calling ERC721_transferFrom / ERC721_safeTransferFrom directly will be approved, and can steal any tokens.

A short-term fix is for ERC721_transferFrom and ERC721_safeTransferFrom to not accept the zero address as caller. However, this will prevent anyone from using these functionalities without going through a contract.

**Comment by andrew-fleming** [comment]
Hey, thank you so much for pointing this out! A prompt fix is forthcoming.

**Comment by martriay** [comment]
> However, this will prevent anyone from using these functionalities without going through a contract.

Do you see this as a problem? I think once fees are mandatory there will be no way to interact directly with contracts, unless they're implemented explicitly to sponsor user interaction in which case they can also handle this.

**Comment by smonicas** [comment]
> Do you see this as a problem? 

No not a problem just a consideration.
