### ISSUE TITLE
ERC721 TokenURI to struct of felts for larger character limit

### ISSUE THREAD

**Issue by rzmahmood** [OpenZeppelin/cairo-contracts#191]
**🧐 Motivation**

Hey team! I was just thinking about the TokenURI in ERC721 and the 31 character limitation which is unrealistic for any reasonable tokenURI, e.g. IPFS url and hope we can find a solution or workaround to get a reasonable size.

**📝 Details**
I propose the TokenURI for ERC721 is changed from a single felt to a struct with 3 felts. This will ensure that we can encode a reasonable sized URI while also preventing users from doing arbitrary size URIs with an array of felts.

For example, QASR has their own implementation here: https://github.com/mortimr/qasr/blob/master/starknet/contracts/erc721.cairo

We could do the following changes in `ERC721_base.cairo`
```c
struct TokenURI:
    member a : felt
    member b : felt
    member c : felt
end
```

```c
@storage_var
func ERC721_token_uri(token_id: Uint256) -> (token_uri: TokenURI):
end
```

```c
func ERC721_tokenURI{
        syscall_ptr: felt*,
        pedersen_ptr: HashBuiltin*,
        range_check_ptr
    }(token_id: Uint256) -> (token_uri: TokenURI):
    let (exists) = _exists(token_id)
    assert exists = TRUE

    # if tokenURI is not set, it will return 0
    let (token_uri) = ERC721_token_uri.read(token_id)
    return (token_uri)
end

```
```c
func ERC721_setTokenURI{
        syscall_ptr: felt*,
        pedersen_ptr: HashBuiltin*,
        range_check_ptr
    }(token_id: Uint256, token_uri: TokenURI):
    uint256_check(token_id)
    let (exists) = _exists(token_id)
    assert exists = TRUE

    ERC721_token_uri.write(token_id, token_uri)
    return ()
end
```

This would give us enough characters for any reasonable URI

Happy to make the PR for this as well

**Comment by rzmahmood** [comment]
I'll be looking into string representation libraries and will come back to this

**Comment by rzmahmood** [comment]
Have you guys seen this library? Heres the link to some examples: https://github.com/sekai-studio/starknet-libs/blob/main/examples/String_Examples.cairo

@andrew-fleming @martriay ?

**Comment by frangio** [comment]
> this multi-felt URI implementation would not be an actual concatenation (thus deviating from the standard)

The issue I see is actually that there is no standard (yet, and as far as I know) for ABI-encoding of strings. Even if we define a sound way to represent strings using multiple felts, this isn't worth much unless the tooling and ecosystem can properly encode and decode them.

Our options are to wait for Starkware to define this standard, or to lead that effort ourselves or someone else.
