### ISSUE TITLE
Refactor `token_id` to `tokenId`

### ISSUE THREAD

**Issue by rzmahmood** [OpenZeppelin/cairo-contracts#199]
**🧐 Motivation**

**📝 Details**
We use `tokenId` in public contracts like `ERC721.cairo` but use `token_id` in files like `erc721/library.cairo`. In solidity we see that `tokenId` is always used.
I believe we should be consistent with this. 

**📝 Details**

Recommended practice by the cairo docs is to do something like this:
`ERC721_ownerOf(token_id=tokenId)` which doesn't look great

Happy to make a PR for this if we agree

**Comment by martriay** [comment]
We only use camelCase on public interfaces that aim to comply with EIP standards, while snake_case in any other place. You can read more about on old discussions like https://github.com/OpenZeppelin/cairo-contracts/discussions/34

**Comment by rzmahmood** [comment]
Great thanks, will close this
