### ISSUE TITLE
Optimize ERC721_Enumerable library

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/cairo-contracts#207]
Optimizing the ERC721_Enumerable library should be revisited once StarkNet adds storage arrays.

**Comment by frangio** [comment]
@andrew-fleming What did you mean by "storage arrays"? Does #207 resolve this or is it unrelated?

**Comment by andrew-fleming** [comment]
@frangio No, it's unrelated. This issue was for if/when an actual array can be set as storage (as opposed to pseudo arrays with enumerated keys). Sorry, I should have been more specific with both of these titles
