### ISSUE TITLE
Move interface ids to `constants.cairo`

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/cairo-contracts#208]
- [ ] `account/library.cairo`
- [ ] `introspection/ERC165.cairo`
- [ ] `token/erc721/utils/ERC721_Holder.cairo`
- [ ] `token/erc721/library.cairo`
- [ ] `token/erc721_enumerable/library.cairo`

All contracts that use interface ids should import them from `constants.cairo`

**Comment by martriay** [comment]
although I suggested this myself, I'm not convinced there's an advantage on doing so. Is there a gain in legibility? are interface ids reused across files?

**Comment by martriay** [comment]
Mhh, it does make sense and to make it available to users.
