### ISSUE TITLE
Add basic multisig Account

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#21]
This should be implemented in the [`is_valid_signature` function](https://github.com/OpenZeppelin/cairo-contracts/blob/db115ccf0a9955e05e15f5c14dbd18b4dae6974c/contracts/Account.cairo#L132-L159).

This is how it looks for single signature accounts:

```
@view
func is_valid_signature{
        storage_ptr: Storage*,
        pedersen_ptr: HashBuiltin*,
        ecdsa_ptr: SignatureBuiltin*,
        syscall_ptr: felt*,
        range_check_ptr
    } (
        hash: felt,
        signature_len: felt,
        signature: felt*
    ) -> ():
    assert_initialized()
    let (_public_key) = public_key.read()
    # This interface expects a signature pointer and length to make
    # no assumption about signature validation schemes.
    # But this implementation does, and it expects a (sig_r, sig_s) pair.
    let sig_r = signature[0]
    let sig_s = signature[1]

    verify_ecdsa_signature(
        message=hash,
        public_key=_public_key,
        signature_r=sig_r,
        signature_s=sig_s)

    return ()
end
```

**Comment by TAdev0** [comment]
@martriay  may i work on this issue?

**Comment by martriay** [comment]
Really appreciate the energy! But let's focus on closing the other PRs first :)

**Comment by TAdev0** [comment]
@martriay  hi, tell me when we're good to start working on this feature, if no one  else is working on it yet :)

**Comment by martriay** [comment]
some challenges i foresee here is having a different storage struct due to having multiple and not a single owner as our current designs, and how to manage the code duplication if we were to have two different components, etc
