### ISSUE TITLE
erc20/library.cairo "Transfer" event param "_from" not compatible with Starknet Python testing library

### ISSUE THREAD

**Issue by eddiexbank** [OpenZeppelin/cairo-contracts#219]
**📝 Details**

with Starkware official testing Python package: [starkware/starknet/testing/contract_utils.py](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/testing/contract_utils.py) line 100, it encodes processed StarknetTransaction with `namedtuple`. Thus, calling erc20 `Transfer` with current OZ event signature 
```
@event
func Transfer(_from : felt, to : felt, value : Uint256):
end
```
will fail with `ValueError: Field names cannot start with an underscore: '_from'`

**🔢 Code to reproduce bug**

In Python, try calling `Transfer` with this pattern
`tx = await erc20_contract.transfer(10, dst.contract_address).invoke(src)`
given
- erc20_contract = erc20 contract
- src = source account contract
- dst = destination account contract

**Comment by martriay** [comment]
Mhh I see. I honestly always hated how this ended up. @bbrandtom do you think Cairo can release the `from` keyword and make it available? It's a *very* useful one for smart contract programming 😓.

Otherwise, maybe we can change it to `from_` which isn't the best but...

**Comment by milancermak** [comment]
I don't think `from` can be made available, it's used for importing, e.g. `from starkware.cairo.common.alloc import alloc`.

**Comment by martriay** [comment]
Mhhhh right

**Comment by andrew-fleming** [comment]
Is `From` completely out of the question?
```@event
func Transfer(From : felt, to : felt, value : Uint256):
end
```
vs
```@event
func Transfer(from_ : felt, to : felt, value : Uint256):
end
```

**Comment by milancermak** [comment]
To me, that looks too much like a type name (when compared to `Uint256`), but that's [just my opinion](https://giphy.com/gifs/opinion-the-big-lebowski-well-thats-just-like-your-man-26BRrSvJUa0crqw4E).

**Comment by martriay** [comment]
> Yeah, that's fair. I suppose ugly is better than potentially confusing.

Agree. Luckily argument names are not part of Ethereum's ABI specification, so it shouldn't break anything. I'm unsure about the events though.


Agree. LuAgree. Lu

**Comment by eddiexbank** [comment]
Great!
