### ISSUE TITLE
Use TRUE, FALSE from Cairo stdlib

### ISSUE THREAD

**Issue by milancermak** [OpenZeppelin/cairo-contracts#259]
Cairo lang v0.8.0 shipped with [`bool.cairo`](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/bool.cairo) which define TRUE and FALSE. I propose using these instead of the values from [`constants.cairo`](https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/utils/constants.cairo).

If you agree, I can send a PR as well.

**Comment by andrew-fleming** [comment]
Good find, @milancermak! And that'd be great—assuming there's no protest :) I vote for `cairo.bool`.
