### ISSUE TITLE
No MultiCall in code

### ISSUE THREAD

**Issue by microbecode** [OpenZeppelin/cairo-contracts#271]
The documentation at https://github.com/OpenZeppelin/cairo-contracts/blob/main/docs/Account.md#call-and-multicall-format talks about `struct` MultiCall, but in code it's called `AccountCallArray` (https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/account/library.cairo#L34) which even has quite different members. Or at least I wasn't able to find MultiCall anywhere.

Please bring the documentation up to date. Related also to https://github.com/OpenZeppelin/cairo-contracts/issues/258

**Comment by martriay** [comment]
How is this issue different from #258?

**Comment by microbecode** [comment]
Thanks for the feedback!
#258 sounds like a narrow documentation fix. I would actually like for the whole concept to be documented better, but started from another narrow documentation fix, with this issue.
If you want, you can just close this and enlarge the other issue's scope.
