### ISSUE TITLE
Implement `ERC1155`

### ISSUE THREAD

**Issue by AnthonyBuisset** [OpenZeppelin/cairo-contracts#273]
ERC1155 contracts are very useful for GameFi and StakNet is a great environment for on-chain games.
[OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/token/ERC1155) contains several examples that could be implemented in cairo

**Comment by martriay** [comment]
There's a PR for this already :)

https://github.com/OpenZeppelin/cairo-contracts/pull/118

**Comment by AnthonyBuisset** [comment]
Damn, I have been working on it for the past 2 days :-(
Thanks @martriay  for letting me know.
At least I have gained experience in cairo with this work :-D

Side question: I have seen that ERC721 uses Uint256 for token id and PR #118 uses felt.

What is OpenZeppelin recommendation for that ? 
Personally I prefer felt as it is natively supported in cairo, but I would appreciate your opinion.

**Comment by martriay** [comment]
So sorry to hear that 😬 

That's one of the reasons we recommend opening an issue before producing any work, not just to avoid race conditions but also to agree on implementation details beforehand and streamline the whole process, and not waste time. At least you learned some Cairo though!

You can also reach out the the people working on that PR and cooperate with them, maybe also nudging them a bit, heh 😋 

> Side question: I have seen that ERC721 uses Uint256 for token id and PR #118 uses felt.

I know the [working (not yet pushed) implementation](https://github.com/OpenZeppelin/cairo-contracts/pull/118#issuecomment-1079899181) uses Uint256 and that's what I prefer, to comply as much as possible with the EIP1155 interface.
