### ISSUE TITLE
Add two step ownership transfer

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#304]
See [Solidity's implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3620).

**Comment by ctrlc03** [comment]
Closed previous PR and submitted [this](https://github.com/OpenZeppelin/cairo-contracts/pull/505)

**Comment by milancermak** [comment]
Hi, I see this feature is not high prio right now, but can I work on it? I have a need for it and I think it will be pretty easy to add it thanks to components.

**Comment by martriay** [comment]
@milancermak yes! please go ahead
