### ISSUE TITLE
Deploy account util

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#333]
we'd be so happy if we turned 

```python
my_account = await starknet.deploy(
    "contracts/Account.cairo",
    constructor_calldata=[my_signer.public_key]
)
```

into

```python
my_account = await Account.deploy(my_signer.public_key)
```

Not sure if it makes sense to have this here or Nile tbh.

**Comment by 0xSidius** [comment]
Nile

> we'd be so happy if we turned
> 
> ```python
> my_account = await starknet.deploy(
>     "contracts/Account.cairo",
>     constructor_calldata=[my_signer.public_key]
> )
> ```
> 
> into
> 
> ```python
> my_account = await Account.deploy(my_signer.public_key)
> ```
> 
> Not sure if it makes sense to have this here or Nile tbh.
