### ISSUE TITLE
Vesting contract

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#334]

**Comment by zpano** [comment]
How can i distrubite code for this feature?

**Comment by ericnordelo** [comment]
Hey @zpano, we appreciate and are always open to contributions. Check our [CONTRIBUTING](https://github.com/OpenZeppelin/cairo-contracts/blob/main/CONTRIBUTING.md) guidelines as a reference, and feel free to open a PR any time.
