### ISSUE TITLE
Nonce abstraction

### ISSUE THREAD

**Issue by Pet3ris** [OpenZeppelin/cairo-contracts#354]
The current Account contract implementation increments the nonce on each execution. Alternatively, it could provide a separate function for explicit nonce incrementation that could be used by a user to clear pending transactions.

As a benefit - transactions that don’t need to be strictly ordered would not pay for the additional storage change of incrementing the nonce.

Have you considered providing this as a default/alternative implementation?

P.S. As one use case, we’d be interested to experiment with this for our keeper accounts.

**Comment by microbecode** [comment]
I wouldn't say it's a matter of ordering - it's a matter of replayability. Nonces are there to prevent replaying the same transaction: no nonce can be used (executed) twice.

Personally, I feel there probably are valid use cases for nonceless variants (not familiar with keeper accounts). But also, there are lots of different (weird) things that become possible with account contracts. Might be difficult to maintain all of those in a place like OZ.

P.S. I'm not from OZ, but just voicing my opinion.

**Comment by martriay** [comment]
> it could provide a separate function for explicit nonce incrementation that could be used by a user to clear pending transactions

I prefer not to add extra functionality if this can be achieved with the existing one already at no additional cost. The main focus of these contracts is security, especially in such a critical place like accounts, therefore I prefer to maintain the bug/attack surface at the minimum.

> Might be difficult to maintain all of those in a place like OZ.

+1

**Comment by martriay** [comment]
Since starkware [plans to move nonce functionality into the base system](https://starkware.notion.site/starkware/StarkNet-0-10-0-4ac978234c384a30a195ce4070461257#f62402de3ac14f94800b5b0a37b7ef5d), this is no longer viable.
