### ISSUE TITLE
[Extensibility] Rename `internal` to `private`

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#372]
In our [extensibility pattern](https://github.com/OpenZeppelin/cairo-contracts/blob/main/docs/Extensibility.md), `private` makes much more sense than `internal` for those functions not meant to be used outside the module or imported by contracts.

I would also define `internal` functions as those that **are** part of the public API of a library, but its usage is not encouraged since it requires understanding the implementation, such is the case of `_transfer` in ERC20 or `_unsafe_execute` in the Account library.

I know this kind of name-swaps is heavily discouraged since we're taking an existing word in this framework and changing its meaning to a completely different one, but I believe it's the right choice and that it's soon enough for us to do so.

**Comment by nikitastupin** [comment]
Heavy plus for using `private` over `internal` but I'm confused with using `internal` for the public API (that's not really public) 🤔 I don't have an alternative though 🤷‍♂️
