### ISSUE TITLE
Implement deployer contract

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#384]
Implement the [Universal Deployer Contract](https://community.starknet.io/t/universal-deployer-contract-proposal/1864).

**Comment by Arcticae** [comment]
Hey guys - do you plan on adding the deployment syscall feature to the account contract (like starkware's contract does)?
https://github.com/starkware-libs/cairo-lang/blob/13cef109cd811474de114925ee61fd5ac84a25eb/src/starkware/starknet/third_party/open_zeppelin/Account.cairo#L204

**Comment by martriay** [comment]
[Nope](https://community.starknet.io/t/universal-deployer-contract-proposal/1864)
