### ISSUE TITLE
Add `assert_not_initialized` and `assert_initialized` to initializable.cairo

### ISSUE THREAD

**Issue by 0xtonysprocket** [OpenZeppelin/cairo-contracts#393]
**🧐 Motivation**
It is easy to import Initializable library and is used often especially with proxys but lacks these assert functions

**Comment by martriay** [comment]
I don't think that's present even in the [solidity version of Contracts](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/contracts/Initializable.sol). Can you share an example of how would you use this feature?

**Comment by 0xtonysprocket** [comment]
Ah, this made me go look at the initialize function again and I see it performs this check internally. I guess the only time this would actually be useful is to make sure that other functions aren't called before the contract is initialized. Probably not as important as I thought. Thanks for your reply!

**Comment by martriay** [comment]
Closing this since it will not be relevant anymore after the ongoing Cairo 1.0 migration. If you think this is a mistake, feel free to open a new issue.
