### ISSUE TITLE
bump to Cairo v0.10.0

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#403]
- [ ] add the validate and validate_declare functions
- [ ] remove nonce handling
- [ ] refactor execute
  - [ ] remove the validation part (this also means asserting that the caller is zero in execute)
  - [ ] check that version > 0 (to avoid the case of bypassing validation via backwards compatibility)

also account for [syntax changes](https://starkware.notion.site/starkware/StarkNet-0-10-0-4ac978234c384a30a195ce4070461257)
> - The body of a function will now be defined inside curly brackets.
> - Every statement must end with a semicolon.
> - Structs will be defined inside curly brackets, the `member` keyword is removed.

**Comment by frangio** [comment]
Wizard will need to adapt to syntax changes as well. See https://github.com/OpenZeppelin/contracts-wizard/issues/173
