### ISSUE TITLE
Add docsite preview to CI

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#412]
The [docs-utils project](https://github.com/OpenZeppelin/docs-utils#setting-up-docs-previews-on-pull-requests) suggests a javascript-based solution to implement docsite previews on PRs. This issue aims to adapt it to this repository for the relevant PRs.

**Comment by frangio** [comment]
I think we can still use docs-utils just using `npx` so we don't have to add a package.json.

**Comment by frangio** [comment]
Expanding on the above: as long as Node.js is installed, `npx` is available and can be used to run docs-utils without installing it. It would look something like `npx @openzeppelin/docs-utils -- -c docs` (`--` may or may not be necessary).

On GitHub Actions you need to add `use: actions/setup-node`.

**Comment by martriay** [comment]
fixed by #459
