### ISSUE TITLE
Fix links in doc navigation page

### ISSUE THREAD

**Issue by achab** [OpenZeppelin/cairo-contracts#435]
The navigation page of the documentation is currently exposed dead links.

**📝 Details**

Links have not been updated to match the current structure. We should update them to enable easy navigation.

**🔢 Code to reproduce bug**

No code, just click on links on this page: https://github.com/OpenZeppelin/cairo-contracts/blob/main/docs/modules/ROOT/nav.adoc.

**Comment by martriay** [comment]
I don't think there's an issue with the new structure. Those links are meant to work on [our documentation site](https://docs.openzeppelin.com/contracts-cairo/0.3.1/proxies) and it does.

**Comment by martriay** [comment]
Hehe that's why we ask issues first, PRs later ^^
