### ISSUE TITLE
Adding Hooks

### ISSUE THREAD

**Issue by 192-sean** [OpenZeppelin/cairo-contracts#44]
Add Dev Hook Functions
---------------------------------------------

Another feature request regarding the extensibility of Starknet smart contracts. Probably further down the list of things needed right now but good to be cognizant of while moving forward. The OpenZeppelin's Solidity ERC20 uses _beforeTokenTransfer and _afterTokenTransfer functions allowing functionality such as [ERC20Pausable](https://docs.openzeppelin.com/contracts/3.x/api/token/erc20#ERC20Pausable).

**Comment by martriay** [comment]
Thanks for opening this issue. This is definitely something we want to solve at some point but it's unclear yet how hooks should be implemented in Cairo, and it's not in our short term roadmap to solve it.

In the meantime, we suggest simply extending the `_transfer` function with the custom logic.

**Comment by martriay** [comment]
This is partially solved by [the extensibility model](https://github.com/OpenZeppelin/cairo-contracts/pull/98). Will update the documentation to further expand on this aspect of the model. Closing this.
