### ISSUE TITLE
DOC: Add cairo-nile dependency to setup.cfg

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#441]
Nile is a requirement for the **Development** section, but is not installed with `pip install .` (the dependency is not set in setup.cfg).

**Comment by ericnordelo** [comment]
In README.md it instructs to compile the contracts using Nile after executing `python -m pip install .`. But this won't work if you haven't installed Nile previously (because it is not installed in the previous step).

Maybe adding an entry to the README.md to instruct installing Nile would be helpful.

**Comment by martriay** [comment]
Closing this since it will not be relevant anymore after the ongoing Cairo 1.0 migration. If you think this is a mistake, feel free to open a new issue.
