### ISSUE TITLE
FEAT: Integrate docs-utils into docsite

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#453]
Instead for installing Antora globally to handle docs, follow package suggestion of local installation:

_**"We strongly recommend that you install Antora within the playbook project. This strategy makes it easier to manage the version of Antora. It also ensures that the version of Antora matches the version for which the playbook was made."**_

**Comment by martriay** [comment]
Integrating with [docs-utils](https://github.com/OpenZeppelin/docs-utils) will do. Renamed the issue appropriately.
