### ISSUE TITLE
Define (or select) and follow a code format for cairo contracts

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#454]
Document this code format practices in the repository.

**Comment by milancermak** [comment]
Cairo comes with a formatting tool, `cairo-format`. It would be great it you would adopt it as well. There's a myriad of reasons why using the standard formatter is preferrable:
* It completely prevents discussions like [this one](https://github.com/OpenZeppelin/cairo-contracts/pull/449#discussion_r962421476). That time and energy is better spent elsewhere.
* It's easier for contributors (also illustrated in the previous point). It's common to have an IDE set up to "format on save" using `cairo-format`. If you'd go with a different approach, a contributor has to reconfigure their IDE setup just for this repo or reformat manually or install whatever other tool you'll use. Anecdotally, it prevented me opening up some small PRs in the past, 'cause I just couldn't be bothered with the setup.
* It's future proof. It's feasible that there will be more syntax changes to the language, but `cairo-format` will be always up to date.
* It's easy to integrate into your CI process and can be done immediately.
* More and more projects in the community are using `cairo-format`. That means developers and auditors are used to how Cairo code looks. A different formatting is distracting. 
* Cairo 1.0 should be open source and I'm assuming `cairo-format` with it as well. If you have any gripes with the formatting, it would be beneficial for everyone to eventually submit a PR and fix it there.

**Comment by martriay** [comment]
Closing this since it will not be relevant anymore after the ongoing Cairo 1.0 migration. If you think this is a mistake, feel free to open a new issue.
