### ISSUE TITLE
Unable to compile `IAccount.cairo` due to re-definition of `__validate_declare__`

### ISSUE THREAD

**Issue by unparalleled-js** [OpenZeppelin/cairo-contracts#465]
Compile the `IAccount.cairo` contract.

**📝 Details**

It would fail to compile the `IAccount.cairo` contract and give this error:

```
openzeppelin/account/IAccount.cairo:22:31: Redefinition of '__main__.IAccount.library_call___validate_declare__.Args.class_hash'.
    func __validate_declare__(class_hash: felt) {
```

**🔢 Code to reproduce bug**

from the `src` directory:

```bash
starknet-compile openzeppelin/account/IAccount.cairo
```

Also tried

```bash
starknet-compile openzeppelin/account/IAccount.cairo --account
```

**Comment by unparalleled-js** [comment]
Further digging: realized that the problem is with the argument name `class_hash`

**Comment by unparalleled-js** [comment]
The part I do not understand is why it does not fail in `Account.cairo` or `EthAccount.cairo`. Is this because they require `--account` flag when compiling and thus can break this rule?

**Comment by andrew-fleming** [comment]
Thanks for bringing this up @unparalleled-js!

> Is this because they require --account flag when compiling and thus can break this rule?

From what I can gather, account contracts _must_ have `__validate_declare__` with the `class_hash` exactly. If you change `class_hash` in the actual contract, you get this error:

```
'__validate_declare__' function must have one argument `class_hash: felt`.
```

I suppose your solution of changing `class_hash` to `cls_hash` in the interface could work for now, but it might be worth bringing up to SW. @martriay @ericnordelo thoughts?

**Comment by unparalleled-js** [comment]
I created the issue in Cairo-lang here: https://github.com/starkware-libs/cairo-lang/issues/100

**Comment by rzmahmood** [comment]
Just for awareness, this is blocking us at Immutable currently. Would recommend the temp solution of `cls_hash` as Starkware may be slow to adjust
