### ISSUE TITLE
Error compiling IAccount.cairo

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#487]
Trying to compile with `nile compile --directory src` raises the following error:

```
Compiling src/openzeppelin/account/IAccount.cairo
Account contracts must have external functions named {'__validate_declare__', '__validate__', '__execute__'}, found: [].
```

**Comment by ericnordelo** [comment]
Could be related with #465

**Comment by marlon-wiprud** [comment]
Any updates here or suggested workarounds?

**Comment by ericnordelo** [comment]
Hi @marlon-wiprud, a workaround until an update is released is to change the name of the file containing the interface to something not finished with Account (so starknet compiler doesn't recognize it as an account contract).

Rename IAccount.cairo to AccountInterface.cairo.

**Comment by marlon-wiprud** [comment]
> Hi @marlon-wiprud, a workaround until an update is released is to change the name of the file containing the interface to something not finished with Account (so starknet compiler doesn't recognize it as an account contract).
> 
> Rename IAccount.cairo to AccountInterface.cairo.

This worked, thank you!

**Comment by martriay** [comment]
Closing this since it will not be relevant anymore after the ongoing Cairo 1.0 migration. If you think this is a mistake, feel free to open a new issue.
