### ISSUE TITLE
Standardize format for library error messages

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#488]
Currently, we have some small inconsistencies like `Account: no reentrant call` and `ReentrancyGuard: reentrant call`, that is, for example, an inconsistency between **describing the expected behavior** vs **describing the issue**.

I think we should always use the **describing the issue** version (`ReentrancyGuard: reentrant call` in the example), besides following the "{namspace}: {issue}" format and always in the present tense.

We can add an entry to the CONTRIBUTING guide for this, what are your thoughts @martriay @andrew-fleming?

**Comment by andrew-fleming** [comment]
No arguments from me—I agree with using the **describing the issue** approach and keeping the error messages consistent. If this is accepted, I'd suggest that we be mindful to try and include these changes before the next breaking-changes release

**Comment by martriay** [comment]
Superseded by #696
