### ISSUE TITLE
Add formatter and linter for python tests

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#491]
- [ ] Add and update tox entries.
- [ ] Update CI (add checks)
- [ ] Update CONTRIBUTING guide.

**Comment by ef3n9r98** [comment]
Hi @ericnordelo, I know some devs who'd be interested in working on this. Is there a budget for fixing this issue, and if so, how much? 

I'd put this issue up on [OpenQ](http://www.openq.dev/).

Thanks!

**Comment by martriay** [comment]
hello @ef3n9r98! thanks, but we don't currently have budget allocated to incentivize contributions.

**Comment by martriay** [comment]
Closing this since it will not be relevant anymore after the ongoing Cairo 1.0 migration. If you think this is a mistake, feel free to open a new issue.
