### ISSUE TITLE
Is the git tagging scheme applied as intended?

### ISSUE THREAD

**Issue by FabijanC** [OpenZeppelin/cairo-contracts#501]
I see this PR was merged recently: https://github.com/OpenZeppelin/cairo-contracts/pull/493
But the result looks suspicious to me. E.g. browsing the repo at tag v0.5.0, [the source file of IAccount](https://github.com/OpenZeppelin/cairo-contracts/blob/v0.5.0/src/openzeppelin/account/IAccount.cairo) has v0.4.0 specified in its SPDX comment.

**Comment by martriay** [comment]
That PR had a bug and we had to revert it to release. It will be reopened and properly fixed but in a future release.

**Comment by FabijanC** [comment]
@martriay Does the different SPDX comment (or actually any comment) affect the resulting class hash? I can check later, but just if you or somebody else already knows.

**Comment by FabijanC** [comment]
More importantly, which version will be whitelisted on mainnet? The one with the correct SPDX comment or the one coming from the correct git tag?

**Comment by ericnordelo** [comment]
> More importantly, which version will be whitelisted on mainnet? The one with the correct SPDX comment or the one coming from the correct git tag?

Hi @FabijanC, the one with the correct SPDX comment was the one sent to the whitelist.
