### ISSUE TITLE
Fix version bump for distribution (for good)

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#502]
Echoing https://github.com/OpenZeppelin/cairo-contracts/issues/501, https://github.com/OpenZeppelin/cairo-contracts/pull/493 was not properly resolved.

Also, @ericnordelo pointed out that:

> the script name in RELEASING uses an underscore instead, it should be:
> ```python scripts/update_version.py v0.5.1```

**Comment by ericnordelo** [comment]
I think we should fix the current RELEASING guide in this issue as well. The process currently described is not well defined:

```
(1) Write a changelog.

(2) Run version bump script with the new version as an argument and open a PR.
```

Run version script on which branch? and open a PR from which branch?

```
(3) Create and push a release branch.

git checkout -b release-v0.5.1
git push release-v0.5.1

(4) Checkout the branch to be released. This should be main except in the event of a hotfix. For hotfixes, checkout the latest release branch.
```

Should we merge the PR from step 2 without reviews? Why do we need to push a release branch?

**Comment by martriay** [comment]
> Run version script on which branch? and open a PR from which branch?

releases are always from `main` (it's documented throughout all our processes -- point 4 in this file) so it's understood the version script has to be run on top if it, we can document it if you think it's unclear. as of specifying from which branch to open the PR, i don't think there's much value in it since the result is always the same, no?

> Should we merge the PR from step 2 without reviews?

yes, i noticed this wasn't well thought of after your PR too. my first though when i saw the PR was it wasn't necessary because we trusted the script already, but i guess letting it pass through is not safe since the PR could contain a human mistake in it. so i vote yes.

> Why do we need to push a release branch?

see [this discussion](https://github.com/OpenZeppelin/cairo-contracts/pull/520#discussion_r1030471541)

**Comment by ericnordelo** [comment]
> > Why do we need to push a release branch?
> 
> see [this discussion](https://github.com/OpenZeppelin/cairo-contracts/pull/520#discussion_r1030471541)

Got it. I think it would be helpful to use tags and avoid pushing a publish branch just for that in the future. For now, maybe mention this requirement in the RELEASING, so the why is clear?
