### ISSUE TITLE
Simplify memoization testing pattern

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/cairo-contracts#506]
The [memoization pattern](https://docs.openzeppelin.com/contracts-cairo/0.5.0/utilities#memoization) generally uses three fixtures (`contract_classes`, `<target>_init`, and `<target>_factory`). It'd be really great if we could abstract most of this logic out in order to simplify the test setup process.

**Comment by andrew-fleming** [comment]
One ambitious approach might be to create a hook that returns a dynamically created fixture. Here's the flow idea:
- Create contract deployment instances.
- The hook populates a fixture with cached contracts.
- Return the references to cached contracts from dynamic fixture.

I'm not sure if this is even possible while maintaining the performance benefit of this pattern (which is also the whole point of the pattern). Open to any ideas that will remove some of this boilerplate:

```
@pytest.fixture(scope='module')
def contract_classes():
    account_cls = Account.get_class
    erc20_cls = get_contract_class('ERC20')

    return account_cls, erc20_cls


@pytest.fixture(scope='module')
async def erc20_init(contract_classes):
    account_cls, erc20_cls = contract_classes
    starknet = await State.init()
    account1 = await Account.deploy(signer.public_key)
    account2 = await Account.deploy(signer.public_key)
    erc20 = await starknet.deploy(
        contract_class=erc20_cls,
        constructor_calldata=[
            NAME,
            SYMBOL,
            DECIMALS,
            *INIT_SUPPLY,
            account1.contract_address,        # recipient
        ]
    )
    return (
        starknet.state,
        account1,
        account2,
        erc20
    )


@pytest.fixture
def contract_factory(contract_classes, erc20_init):
    account_cls, erc20_cls = contract_classes
    state, account1, account2, erc20 = erc20_init
    _state = state.copy()
    account1 = cached_contract(_state, account_cls, account1)
    account2 = cached_contract(_state, account_cls, account2)
    erc20 = cached_contract(_state, erc20_cls, erc20)
    return erc20, account1, account2
```

**Comment by martriay** [comment]
Closing this since it will not be relevant anymore after the ongoing Cairo 1.0 migration. If you think this is a mistake, feel free to open a new issue.
