### ISSUE TITLE
Counters library for incremental token id

### ISSUE THREAD

**Issue by remiroyc** [OpenZeppelin/cairo-contracts#507]
## Motivation
The mint function of the actual ERC721 contract requires a token id: 
```
func _mint{pedersen_ptr: HashBuiltin*, syscall_ptr: felt*, range_check_ptr}(to: felt, token_id: Uint256) { }
```
In most cases, users who want to port their nft collections from mainnet to starknet will need incremental token ids.

 

## Details
Token ids should not be assumed to follow any pattern as described by [EIP72](https://eips.ethereum.org/EIPS/eip-721). 
That's why I propose to introduce a Counters library and a new erc721 preset with updated documentation as it's done for the [solidity version](https://docs.openzeppelin.com/contracts/2.x/erc721#constructing_an_erc721_token_contract).

**Comment by andrew-fleming** [comment]
I agree that it's quite simple. From a convenience standpoint, however, I wouldn't hate having a Counter lib. Plus, the ReentrancyMock is already using one: https://github.com/OpenZeppelin/cairo-contracts/blob/main/tests/mocks/ReentrancyMock.cairo

Either way, +1 to an auto-incremental ERC721 preset.
