### ISSUE TITLE
Package bug see old code version

### ISSUE THREAD

**Issue by 0xAurelou** [OpenZeppelin/cairo-contracts#510]
Hello OZ,

**📝 Details**
I wanted to install openzeppelin-cairo-contracts 0.5.0 version, it worked for me but when I go to the source code directly on my .env all the header show that I have the 0.4 version (first screen attached)
![image](https://user-images.githubusercontent.com/63618058/199742590-7653af68-0060-4b96-bab8-543e34fc9b37.png)

**🔢 Code to reproduce bug**

First I tried to ``pip install openzeppelin-cairo-contracts==0.5.0 --no-cache-dir``
After I pip show it in order to be sure my version have been updated
![image](https://user-images.githubusercontent.com/63618058/199743123-c334a35e-603d-4ab6-b766-635b122e36ef.png)
The source code:
![image](https://user-images.githubusercontent.com/63618058/199743184-073b973b-63e4-4912-b0c8-7cf342ba2f04.png)

Thanks for the help :rocket:

**Comment by martriay** [comment]
Hey there! Contracts are fine, it's an issue we had with the version bump script, [to be fixed soon](https://github.com/OpenZeppelin/cairo-contracts/issues/502)!

**Comment by 0xAurelou** [comment]
Thanks for the answer Martin, don't hesitate to close this issue when it has been fixed :+1:

**Comment by martriay** [comment]
Closing this since it will not be relevant anymore after the ongoing Cairo 1.0 migration. If you think this is a mistake, feel free to open a new issue.
