### ISSUE TITLE
ETH Transfer Reverted

### ISSUE THREAD

**Issue by yavuzkocca** [OpenZeppelin/cairo-contracts#516]
Error in the called contract (0x69aac6a8f628c08949171cd81666d255629c040073114262c041b6e26caf360):
Error at pc=0:156:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:3427)
Unknown location (pc=0:3384)
Unknown location (pc=0:610)

Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):
Error at pc=0:104:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:1678)
Unknown location (pc=0:1664)

Error in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):
Error at pc=0:9:
Got an exception while executing a hint.
Cairo traceback (most recent call last):
Unknown location (pc=0:1434)
Unknown location (pc=0:1386)

Traceback (most recent call last):
  File "<hint1>", line 3, in <module>
AssertionError: assert_not_zero failed: 0 = 0.

**Comment by martriay** [comment]
This issue has no comment, context, nor explanation.
