### ISSUE TITLE
Migrate UDC to Cairo 1+

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#552]

**Comment by FabijanC** [comment]
Any plans to resolve this? Revive #610?
cc: @mikiw

**Comment by martriay** [comment]
This is planned as part of the ["later" milestone](https://github.com/OpenZeppelin/cairo-contracts/milestone/4), which usually means it's roughly between 9 to 12 weeks away -- in all honesty, this is not usually true since we periodically reassess priorities and milestones and stuff might get deprioritized (new issues arise, some others take longer, etc.) so it's not a super strong commitment for you to plan on top of.

That being said, the UDC was blocked until not long ago because of lacking testing framework capabilities, specifically around deployment address differences between mainnet and test framework, which should be resolved as of now.
More generally, the UDC was never a priority in the Cairo 1+ migration due to the Cairo 0 version working just fine. Regenesis is the only deadline we have, and its date is uncertain.

Do you need this before? May I ask why? Better understanding your needs will help us inform better and prioritize our roadmap.

**Comment by FabijanC** [comment]
Thanks for the reply!

Starkware was planning on using starknet-devnet-rs for their testing simulation, and asked us to update the predeployed ERC20 and accounts to Cairo 1. Devnet already offers OZ Cairo 1 accounts, but not by default.

Anyway, I was thinking of completely switching all predeployed contracts to Cairo 1, which would mean only UDC remains.

**Comment by martriay** [comment]
Thanks for providing more context. I'll make sure to keep you updated on this one.
