### ISSUE TITLE
Account contract class hash?

### ISSUE THREAD

**Issue by xJonathanLEI** [OpenZeppelin/cairo-contracts#554]
_(This is more of a question than a bug report)_

Hi! I'm working on supporting account contract deployment in [starkli](https://github.com/xJonathanLEI/starkli). The first "flavor" to support is the OpenZeppelin account contract. However, to support it I need the "official" class hash to be used in the `DeployAccount` transaction type.

I couldn't find any official hashes so I did it myself. Based on the [hashes generated](https://github.com/xJonathanLEI/starknet-rs/blob/b5a0b92710c44e13108a39d1afbfd36a39fb6ed7/starknet-core/test-data/contracts/artifacts/oz_account.hashes.json) in the `starknet-rs` repo by compiling and hashing it inside the `shardlabs/cairo-cli:0.10.3` Docker image, the account contract hash for `v0.6.1` is `0x508fc648f7dc864be1242384cc819f0d23bfeea97b5216923ab769e103c9775`.

However, when I look up this hash on Starkscan, it's only declared on `goerli-1` (by my `starknet-rs` test cases), and also only deployed by my `starknet-rs` tests. I wonder why this is the case.

Is it really the case that no one but `starknet-rs` is using the v0.6.1 oz account contract? Or is it that I'm getting a different (potentially wrong) class hash here?

Thanks in advance!

**Comment by crypt0xyc** [comment]
Using the Starkware/Cairo Python libraries together with the latest OpenZeppelin contracts (from here: https://github.com/OpenZeppelin/cairo-contracts), I arrive at the same result for the class hash as you got.

Would also be interested to understand why there seems to be no usage of the v0.6.1 account contracts as of yet.

**Comment by ericnordelo** [comment]
Hi @xJonathanLEI. 

> I couldn't find any official hashes so I did it myself. Based on the [hashes generated](https://github.com/xJonathanLEI/starknet-rs/blob/b5a0b92710c44e13108a39d1afbfd36a39fb6ed7/starknet-core/test-data/contracts/artifacts/oz_account.hashes.json) in the starknet-rs repo by compiling and hashing it inside the shardlabs/cairo-cli:0.10.3 Docker image, the account contract hash for v0.6.1 is 0x508fc648f7dc864be1242384cc819f0d23bfeea97b5216923ab769e103c9775.

This class hash is the right one for 0.6.1 compiled with cairo 0.10.3.

> However, when I look up this hash on Starkscan, it's only declared on goerli-1 (by my starknet-rs test cases), and also only deployed by my starknet-rs tests. I wonder why this is the case.

The reason for this is probably nile's artifacts not being updated since cairo 0.10.1. Most of the deployed OZ accounts probably come from nile. This is the current nile artifact class hash 0x058d97f7d76e78f44905cc30cb65b91ea49a4b908a76703c54197bca90f81773.

We've opened [this issue](https://github.com/OpenZeppelin/cairo-contracts/issues/555) for addressing this class hashes mapping.

We will update the nile's artifact as well. Thanks for the comment!

**Comment by xJonathanLEI** [comment]
Got it. Thanks for the answer! I guess I'm the only one doing things the old way and invoking the compiler directly lol.
