### ISSUE TITLE
Document presets corresponding class hashes

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#555]
**🧐 Motivation**

It is hard to find documentation regarding the correct class hash for a preset. With class hashes varying among compiler versions users can get confused about which one to use.

**Comment by martriay** [comment]
We have plans to add class hashes to each preset's documentations. The hard part is how to display a mapping between preset and multiple compiler versions.

**Comment by martriay** [comment]
`Account` seems to be `0x04c6d6cf894f8bc96bb9c525e6853e5483177841f7388f74a46cfda6f028c755` with Cairo 2.2.0
