### ISSUE TITLE
migrate erc1155 contracts

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#572]

**Comment by martriay** [comment]
thanks! @Amxx will be working on it. feel free to review the PR as soon as it's created :)

**Comment by Amxx** [comment]
I wanted to wait until tests are ready to create the PR, but if we can get early review: #594

**Comment by cloudvenger** [comment]
I would like to help on it with the new components release

**Comment by martriay** [comment]
@cloudvenger that's great! Do you think you can have a complete PR (component, tests, docs) within 3~4 weeks?

I'm asking this because we otherwise have time already allocated for this, so we don't step into each other's toes.

**Comment by martriay** [comment]
@cloudvenger said to me
:
>  it should be good to finish it in 3 weeks, starting next week.
