### ISSUE TITLE
Incorrect use of assert_only_role in grant_role and revoke_role

### ISSUE THREAD

**Issue by VenkatTeja** [OpenZeppelin/cairo-contracts#576]
We are passing admin address in assert_only_role while assert_only_role is expecting role. This is causing the assert check to fail. 
```
func grant_role{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
        role: felt, user: felt
    ) {
        let (admin: felt) = get_role_admin(role);
        assert_only_role(admin); <--- shouldn't we be passing role here?
        _grant_role(role, user);
        return ();
    }
```

**📝 Details**
The below function is expecting role as input. It is anyways reading caller itself. 
So, when grant_role is passing admin, `has_role(admin, caller)` is being checked. Hence, this is expected to fail. 
```
func assert_only_role{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
        role: felt
    ) {
        alloc_locals;
        let (caller) = get_caller_address();
        let (authorized) = has_role(role, caller);
        with_attr error_message("AccessControl: caller is missing role {role}") {
            assert authorized = TRUE;
        }
        return ();
    }
```

**🔢 Code to reproduce bug**

Will provide if needed. A simple glance at library code should be clear. 
[link](https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/access/accesscontrol/library.cairo)

**Comment by martriay** [comment]
`assert_only_role` verifies that `caller` has a given `role`.

`grant_role` leverages this function to make sure that `caller` has the `admin` role capable of granting `role` to `user`.

what am i missing?

**Comment by martriay** [comment]
`assert_only_role` verifies that `caller` has a given `role`. `grant_role` leverages this function to make sure that `caller` has the `admin` role capable of granting `role` to `user`. `admin` is not an address, but a special role.

**Comment by martriay** [comment]
`assert_only_role` verifies that `caller` has a given `role`. `_grant_role` leverages this function to make sure that `caller` has the `admin` role capable of granting `role` to `user`. `admin` is not an address, but a special role.

**Comment by VenkatTeja** [comment]
Understood. Sorry for the confusion.
