### ISSUE TITLE
Reorganize contract structure for preset contract compilation

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/cairo-contracts#587]
This depends on how extensibility gets resolved and how Cairo compiles contracts (assuming it will change in the future). As of this writing, the instructed approach to compiling contracts (via `starknet-compile`) is to have one contract per crate and include a `cairo_project.toml` in said crate. It seems extremely redundant for each preset contract to have its own crate; therefore, the contract structure should be (re)organized appropriately.

Source: https://discord.com/channels/793094838509764618/1065544063245365288/1073920751645773882

**Comment by martriay** [comment]
Closing this as it does not apply anymore now that the project is based on scarb. Feel free to reopen if you think it's a mistake.
