### ISSUE TITLE
Use BoundedInt for max_u256

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/cairo-contracts#597]
When [this commit](https://github.com/starkware-libs/cairo/commit/e1165f133db4af0e8f3765c8853f3b86e8e50e58) makes it into a release of cairo, then [these lines](https://github.com/OpenZeppelin/cairo-contracts/blob/a54e98ca74e0d2c127680f3a3ca23d4643eb0ddf/src/openzeppelin/token/erc20.cairo#L198-L206) should be rewritten as
```rust
    fn _spend_allowance(owner: ContractAddress, spender: ContractAddress, amount: u256) {
        let current_allowance = _allowances::read((owner, spender));
        if current_allowance == BoundedInt::max() {
            _approve(owner, spender, current_allowance - amount);
        }
    }
```

**Comment by martriay** [comment]
Closed by #600.
