### ISSUE TITLE
burnable ERC 721 can be reminted after burned

### ISSUE THREAD

**Issue by colinlyguo** [OpenZeppelin/cairo-contracts#601]
burnable ERC 721 can be reminted after burned.

**📝 Details**

When burnable ERC 721 is burned, it can be reminted again.
`Probably similar issues in the solidity version.`
Is it a bit against common sense?

```
Operations below will success:
ERC721._mint(caller_address, token_id);
ERC721._burn(tokenId);
ERC721._mint(caller_address, token_id);
```

**🔢 Code to reproduce bug**

Contract:

```
%lang starknet

from starkware.cairo.common.cairo_builtins import HashBuiltin
from starkware.cairo.common.uint256 import Uint256
from openzeppelin.token.erc721.library import ERC721
from starkware.starknet.common.syscalls import get_caller_address

@constructor
func constructor{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}() {
    ERC721.initializer('MyToken', 'MTK');
    return ();
}

func mint{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
    token_id: Uint256
) {
    let (caller_address) = get_caller_address();
    ERC721._mint(caller_address, token_id);
    return ();
}

@external
func burn{syscall_ptr: felt*, pedersen_ptr: HashBuiltin*, range_check_ptr}(
    tokenId: Uint256
) {
    ERC721._burn(tokenId);
    return ();
}
```

Unit Test:

```
%lang starknet

from src.main import mint, burn
from starkware.cairo.common.cairo_builtins import HashBuiltin
from starkware.cairo.common.uint256 import Uint256

@external
func test_mint_twice{syscall_ptr: felt*, range_check_ptr, pedersen_ptr: HashBuiltin*}() {
    %{ stop_prank_callable = start_prank(1) %}
    %{ expect_revert("TRANSACTION_FAILED", "ERC721: token already minted") %}
    mint(Uint256(1, 0));
    mint(Uint256(1, 0));
    %{ stop_prank_callable() %}
    return ();
}

@external
func test_remint_after_burned{syscall_ptr: felt*, range_check_ptr, pedersen_ptr: HashBuiltin*}() {
    // success: mint after nft 1 is burned.
    %{ stop_prank_callable = start_prank(1) %}
    mint(Uint256(1, 0));
    burn(Uint256(1, 0));
    mint(Uint256(1, 0));
    %{ stop_prank_callable() %}
    return ();
}
```

**Comment by andrew-fleming** [comment]
Hey @colinlyguo! Sorry for the delayed response and thanks for bringing this issue up. This is interesting as it seems obvious that users shouldn't be able to remint burned tokens, but [EIP721](https://eips.ethereum.org/EIPS/eip-721) does not state that burning tokens should be permanent. All that is said regarding minting and burning is: `Creation of NFTs (“minting”) and destruction of NFTs (“burning”) is not included in the specification.` 

Given the common assumption that a burned token can't be reminted, this should be explicitly documented in our preset (sorry 😅).

**Comment by colinlyguo** [comment]
Thank you for your reply, it's very convincing.

A reminder that in the code provided above, I give a code snippet that an ERC 721 token can be reminted after it has burned. So if `a burned token can't be reminted` is explicitly documented, then the code should change, too.

**Comment by martriay** [comment]
> it seems obvious that users shouldn't be able to remint burned tokens (...) Given the common assumption that a burned token can't be reminted (...)

Why does it seem obvious? I'm don't think this a common assumption. As you pointed out the EIP does not hint that in any way.

**Comment by andrew-fleming** [comment]
For me, it's the EIP's use of the word "destruction" and its connotation. Maybe it's not so common.

I also think of these old discussions on the topic https://ethereum.stackexchange.com/questions/73454/erc721-token-burn-and-mint-again

**Comment by martriay** [comment]
That stackexchange topic shows there's a common understanding in that re-minting is indeed possible, no?

**Comment by andrew-fleming** [comment]
Indeed, I'm incorrect in the common-ness of it. I take it back :) 

My point is the question's been asked a few times (and viewed) which implies that it seems like unintended behavior for some—but again, it doesn't appear to be common

**Comment by martriay** [comment]
This seems resolved, feel free to open a new issue if you want to continue discussion.
