### ISSUE TITLE
CANT TEST CAIRO1 contracts

### ISSUE THREAD

**Issue by yusufferdogan** [OpenZeppelin/cairo-contracts#607]
I want to test contracts but it gives an error. I want to know how you run tests.

**🔢 Code to reproduce bug**

`cairo-test --path src/openzeppelin/tests/test_erc20.cairo --starknet
`
and `cairo-test --path src/openzeppelin/tests/test_erc20.cairo ` gives me 
```
error: Identifier not found.
 --> test_erc20.cairo:1:5
use openzeppelin::token::erc20::ERC20;
    ^**********^

Error: failed to compile: src/openzeppelin/tests/test_erc20.cairo
```

**Comment by andrew-fleming** [comment]
Hey @yusufferdogan! You need to target the `openzeppelin` directory e.g.
`cargo run --bin cairo-test -- --starknet --path src/openzeppelin`

You can also just run `make test`
