### ISSUE TITLE
SyscallResultTrait import missing in account

### ISSUE THREAD

**Issue by Th0rgal** [OpenZeppelin/cairo-contracts#630]
Hello,

I was looking at the Account implementation and I couldn't build the _execute_single_call function. Importing ``use starknet::SyscallResultTrait;`` seems to have fixed it for me. It might be because we are not using the same cairo version but I prefer to open an issue if this can help someone.

**Comment by martriay** [comment]
they @Th0rgal, could you share in what context the Account is not building? tests? deployment? are you building this entire repo or a subset of the modules?

sharing more detail of the setup might help us look into this. thanks!
