### ISSUE TITLE
Move SRC5 to drafts directory

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#642]
**🧐 Motivation**
Since SRC5 is still a draft and has not yet been finalized, maybe is worth making this explicit in the repository, because the SNIP  might change (even when is pretty stable).

**📝 Details**
We could add a `draft` directory similar to [what we used to have in Solidity contracts](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/docs-v3.x/contracts/drafts), and add SNIP drafts there, moving them out when get finalized.

**Comment by martriay** [comment]
I'm not sure this distinction is useful at the current stage, since all SNIPs are drafts today
