### ISSUE TITLE
Re-add preset contracts

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#683]
For ERC20 and ERC721 tokens mainly

**Comment by Bal7hazar** [comment]
Hey, I just finished a first Cairo 2 version of our ERC-3525 including presets (using `unsafe_new_contract_state` exclusively).
Feel free to benchmark it if needed for your contracts, I would be glad to help.

**Comment by martriay** [comment]
@Bal7hazar what you mean by benchmarking? performance or to simply compare?

**Comment by Bal7hazar** [comment]
@martriay more about the architecture and the design of the solution

**Comment by martriay** [comment]
Closing this issue as we decided to follow the steps of the Contracts for Solidity repo and leave only basic presets in the repo, and let Wizard for (coming soon for cairo 1+) to cover the rest.
