### ISSUE TITLE
Define `from` and `to` as indexed keys in ERC20 `Transfer` event

### ISSUE THREAD

**Issue by yoga-braavos** [OpenZeppelin/cairo-contracts#697]
https://github.com/OpenZeppelin/cairo-contracts/blob/457b98b10080820ad041980d71b24e7856766336/src/token/erc20/erc20.cairo#L30

Per Ethereum's ERC20 implementation both `to` and `from` are indexed:
https://ethereum.org/en/developers/docs/standards/tokens/erc-20/#events

Now that Cairo supports the `#[key]` attribute, it should be possible to easily align to Ethereum's spec

**Comment by martriay** [comment]
Fixed by #746.
