### ISSUE TITLE
Define `from`, `to` and `token_id` as indexed keys in ERC721 `Transfer` event

### ISSUE THREAD

**Issue by yoga-braavos** [OpenZeppelin/cairo-contracts#698]
https://github.com/OpenZeppelin/cairo-contracts/blob/457b98b10080820ad041980d71b24e7856766336/src/token/erc721/erc721.cairo#L43

Now that Cairo supports the #[key] attribute, it should be possible to easily align to Ethereum's spec:
https://ethereum.org/en/developers/docs/standards/tokens/erc-721/#events

**Comment by martriay** [comment]
Fixed by https://github.com/OpenZeppelin/cairo-contracts/pull/746.
