### ISSUE TITLE
Decimals for ERC20

### ISSUE THREAD

**Issue by Chepelau** [OpenZeppelin/cairo-contracts#711]
**🧐 Motivation**
It would be nice to have configurable decimals in the ERC20 token. Is there any reason for it to not be the case? 

**📝 Details**
Willing to create a PR if there is no reason for the token to not have decimals in the constructor.

**Comment by martriay** [comment]
No reason for it to be fixed. A PR is welcomed!

**Comment by Chepelau** [comment]
Oh I see. Thanks for the explanation! I'll close the issue and PR then?
