### ISSUE TITLE
Cairo 0 -> 1 storage compatibility issues

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#725]
Since the Cairo 1+ migration, storage variable names were renamed from e.g. `ERC20_balances` to just `balances`, resulting in different storage layout and therefore upgradability issues.

But this is just a symptom of another problem.

### Problem

When building on top of different contracts modules (soon [through components v0](https://community.starknet.io/t/cairo-1-contract-syntax-is-evolving/94794#extensibility-and-components-11)), there’s nothing yet preventing them from read/writing to the same storage address inadvertently (i.e. there can be storage collisions).

This has been true since Cairo 0. That’s why the storage variables in our library were prefixed with the module name: to minimize that risk.

### Solution: Components v1

With Components v1 this prefixing will be done automatically by the compiler. Once it’s available, we plan to rename our variables to drop the prefixes. We would provide two components:

1. Components v0 or prefixed storage (`ERC20_balances`)
2. Components v1 or plain storage (`balances`).

Components v1 will be the default in our library, and the v0 retro-compatible version will be supported at least until regenesis to support the Cairo 0 → 1 transition until the very end.

Although it’s up to the users (through Cairo language directives) whether to use a component module as v0 or v1, we’ll encourage using the prefixed component with v0, and the plain component with v1.

**Comment by ArielElp** [comment]
An idea floating around is that with v1 we can think of a way for the contract using components to define their storage layout. This should be flexible enough to handle all kinds of upgradability issues. I'm not sure what it would look like for individual names within the component, but if we can come up with a syntax that makes sense, it could be a good addition.
