### ISSUE TITLE
Write down docs styleguide

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#726]

**Comment by martriay** [comment]
* avoid talking about "us", or the writer as much as possible
* don’t capitalize Account unless it’s a specific contract/impl

**Comment by ericnordelo** [comment]
- Don't include argument types in the header sections for `Utilities`, `Functions`, and `Events`, in the API Reference.

**Comment by andrew-fleming** [comment]
- Write all non-H1 headings in sentence case (only capitalize the first word and proper nouns)

  - For the record, I disagree with this approach. I instead vote for title case in _all_ doc headings because:
    1. Titles of sections are, well, titles and titles should be capitalized IMO.
    2. Consistency with OZ Solidity docs.

**Comment by martriay** [comment]
Use "panics" instead of "reverts" since it's the appropriate term in Starknet.

**Comment by martriay** [comment]
Add `/` at the end of directory names to highlight it's a directory. e.g.: `my_folder/` instead of `my_folder`

**Comment by ericnordelo** [comment]
Always scope IDs by the module name in API Reference. Under the `ERC20` module section, the `name()` function should have the ID: `ERC20-name`

**Comment by ericnordelo** [comment]
Words in html IDs (adoc pages) must be separated by dashes: `ERC20-name` instead of `ERC20::name`

**Comment by martriay** [comment]
> Write all non-H1 headings in sentence case (only capitalize the first word and proper nouns)
> 
> * For the record, I disagree with this approach. I instead vote for title case in _all_ doc headings because:
>   
>   1. Titles of sections are, well, titles and titles should be capitalized IMO.
>   2. Consistency with OZ Solidity docs.

where does this rule come from, if you disagree with it?

**Comment by andrew-fleming** [comment]
>> Write all non-H1 headings in sentence case (only capitalize the first word and proper nouns)

>> - For the record, I disagree with this approach. I instead vote for title case in all doc headings because:

>> - Titles of sections are, well, titles and titles should be capitalized IMO.
>> - Consistency with OZ Solidity docs.

> where does this rule come from, if you disagree with it?

It's just how the old and forthcoming docs are currently written. There's no rule that I'm aware of

**Comment by ericnordelo** [comment]
Put `SRC5 ID` block as a section (similar to Functions and Events) on top of the Interfaces where the ID is usually exposed.

**Comment by martriay** [comment]
to do: resolve [whether we include return values in API definitions](https://github.com/OpenZeppelin/cairo-contracts/pull/689#discussion_r1322310941)

**Comment by martriay** [comment]
something we should evaluate is whether we want to better separate/identify modules in API docs. right now you can only tell whether something is a `mod` (usually lib/preset) or a `trait` (interface) but for its name (e.g. `IAccessControl` vs `AccessControl`). they just display functions.

**Comment by martriay** [comment]
Opened  the "Consider documenting asserts/guards" discussion separately in its own thread: #745

**Comment by martriay** [comment]
to do: decide what to do regarding duplicating function definitions between interface, component, and function definitions in API docs: see discussions [#1](https://github.com/OpenZeppelin/cairo-contracts/pull/863#discussion_r1505263064), [#2](https://github.com/OpenZeppelin/cairo-contracts/pull/920#discussion_r1508373452), and [#3](https://github.com/OpenZeppelin/cairo-contracts/pull/920#discussion_r1508124125)

**Comment by andrew-fleming** [comment]
Closing this issue as this is done internally.
