### ISSUE TITLE
Remove non-standard increase_allowance and decrease_allowance from ERC20

### ISSUE THREAD

**Issue by milancermak** [OpenZeppelin/cairo-contracts#728]
**🧐 Motivation**

The Starknet equivalent to the [recent ERC20 update of Solidity contracts](https://github.com/OpenZeppelin/openzeppelin-contracts/pull/4585). Having these methods is even less necessary on Starknet thanks to AA and multicall. 

Additional benefit of removing them is slightly reduced contract size.

Since the Cairo 2 contracts haven't been officially released, I think it's a good opportunity to squeeze this in 🤞

**Comment by martriay** [comment]
+1, although I don't think this will make it to the release.

**Comment by TAdev0** [comment]
@martriay  I just saw your message on the starknet Cairo core stars channel. May I work on this issue?
Thank you.

**Comment by martriay** [comment]
Thanks for volunteering! You can tackle either this or #841, but I suggest you start with one at the time :)

**Comment by TAdev0** [comment]
sure! will work on this one tonight :)
