### ISSUE TITLE
Draft Wizard for Cairo 1+ specs

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#747]
Once components are out.

**Comment by Nonnyjoe** [comment]
I'll need a little bit of extra description and a reference but if this is still open, I'll like to contribute to this.

**Comment by martriay** [comment]
@Nonnyjoe thanks for the interest, but this specific one requires a bunch of internal coordination within the OpenZeppelin team so it's better for us to tackle.

I appreciate the will to help, I'd suggest you take a look at [our roadmap](https://github.com/orgs/OpenZeppelin/projects/29/) and pick an issue preferably from the `After` milestone onwards.

**Comment by Nonnyjoe** [comment]
That's fine, thank you very much.
