### ISSUE TITLE
remove `safe_transfer_from` and `safeTransferFrom` from the 721 implementation

### ISSUE THREAD

**Issue by moodysalem** [OpenZeppelin/cairo-contracts#748]
this method does not make sense on starknet with account abstraction (simply transfer and then call in the same transaction), and is also exceedingly complicated to implement because:

- supports interface has two different kinds of arguments (SRC5 vs ERC165)
- implementations are checking not just receiver but also account
- camel case and snake case
- handling reverting calls is not even supported by current starknet version

currently oz is basically the standard for cairo interfaces, we don't have any standards written in snake case for example. so please just remove it from the interface and document it in any new standards

https://x.com/sendmoodz/status/1688288181060308992?s=20

**Comment by ericnordelo** [comment]
Hey, thanks for opening up the discussion, a couple of thoughts:

> this method does not make sense on starknet with account abstraction (simply transfer and then call in the same transaction), and is also exceedingly complicated to implement because:

I'm not sure I understand, from this comment it looks like you are against `transfer_and_call` (EIP-677) not against `safe_transfer_from`. The `transfer_from` mechanism has use cases that are not solved by "simply transferring and calling in the same transaction", like allowing a marketplace to transfer tokens without you needing to sign transactions (potentially) with the approve mechanism.

Also, is not clear to me from the comment if you are against the "safe" in `safe_transfer_from`, or against the `transfer_from` mechanism in general. If is against the "safe", are you positive that NFTs being lost in contracts that are not "proper receivers" is not an issue in Starknet?

> supports interface has two different kinds of arguments (SRC5 vs ERC165)

SRC5 should be the standard for introspection, not ERC165 anymore.

> exceedingly complicated to implement because

Not sure that this complication justifies removing a widely adopted mechanism.

**Comment by moodysalem** [comment]
I am asking to remove the "safe" version, not transfer from entirely. Removing transfer from entirely in favor of a transfer is a separate discussion.

Safe transfer from serves two purposes: it prevents transferring to address that cannot receive an NFT, and allows calling the recipient to do stuff with the received NFT (eg uniswap v3 staker). The latter is solved by AA. It is almost never used for the former even on mainnet (these checks can happen off chain to save gas), and it can also be implemented more simply with a different standard that takes advantage of AA (eg call confirm_received_nft after the transfer or call a lens contract that reverts if one of supports interface fails with the given receiver interface ids) 

> Not sure that this complication justifies removing a widely adopted mechanism.

Please share one transaction that uses safe transfer from on starknet mainnet

**Comment by martriay** [comment]
We'll adhere to ERC721 as much as possible and keep `safeTransferFrom`. There's no point in departing even more from the standard which would cause not only confusion but also inconsistent implementations out there, breaking assumptions and interoperability -- the whole purpose behind these standards.

That being said, I do support the design and inclusion of new standards into the library, such as an NFT standard without `safe` functions, but breaking existing ones is not acceptable.

**Comment by moodysalem** [comment]
> We'll adhere to ERC721 as much as possible and keep `safeTransferFrom`. There's no point in departing even more from the standard which would cause not only confusion but also inconsistent implementations out there, breaking assumptions and interoperability -- the whole purpose behind these standards.
> 
> That being said, I do support the design and inclusion of new standards into the library, such as an NFT standard without `safe` functions, but breaking existing ones is not acceptable.

ERC721 is a specification for smart contracts **on Ethereum**, from which OZ's implementation already departs by switching to snake case selectors or replacing ERC165 with SRC5 or returning felts from name/symbol, and so on. [SNIP-3](https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-3.md), which is based on ERC721, is a very simple translation of the ERC721 interface to Cairo 0, written in camel case. Which standard specifically are you implementing?

For Starknet, OZ's Cairo repository is the living standard, at least until the process for SRCs is functional (my [simplified fungible token standard](https://github.com/starknet-io/SNIPs/pull/37/files) was closed without any feedback and my PR to remove the unnecessary methods from SNIP-3 was reverted.)

All due respect, there is an obvious point: it reduces risk of bugs and reduces confusion, because developers don't have to implement or understand a method that is pointless on Starknet, and to my knowledge is not used on Starknet.

**Comment by martriay** [comment]
> Which standard specifically are you implementing?

We're implementing our best attempt to ERC721 in Cairoland, departing from it **only** when we _really really_ need to (type system, introspection mechanisms, etc).

Moody you don't want to implement ERC721, you're trying to rewrite the standard. And with good reasons! But we can't just claim to implement a standard and then offer something completely different.

**Comment by martriay** [comment]
> For Starknet, OZ's Cairo repository is the living standard, at least until the process for SRCs is functional (my [simplified fungible token standard](https://github.com/starknet-io/SNIPs/pull/37/files) was closed without any feedback and my PR to remove the unnecessary methods from SNIP-3 was reverted.)

I feel you, and I think this is the actual problem. SNIP process and management is not currently working and it shows. Consistent with my overall point on this issue, I think your SNIP-3 changes were rightfully reverted since they belong to a different standard, but your simplified proposal should have been discussed and advanced. I urge you to reopen it since they make a lot of sense to me.

> All due respect, there is an obvious point: it reduces risk of bugs and reduces confusion, because developers don't have to implement or understand a method that is pointless on Starknet, and to my knowledge is not used on Starknet.

I agree it's an improvement but we simply cannot rewrite the standard. Interpretations can and should be done as long as they're reasonable and expectable. Removing functions would only break assumptions in a way that supporting different casing of using a slightly modified version of ERC165 (which also aims to be as similar as possible to the EIP) do not. It would require a different name.
