### ISSUE TITLE
Unable to Deploy Extended ERC20 Standard Contract Example

### ISSUE THREAD

**Issue by henryf10h** [OpenZeppelin/cairo-contracts#759]
Hello,

I've been trying to deploy an example that extends the ERC20 standard contract using the starkli tool, but I've encountered some issues.
![image](https://github.com/OpenZeppelin/cairo-contracts/assets/55424527/c930db45-9e2a-4e9e-8747-a4e70d3a04b5)

Steps to Reproduce:

I followed the example provided for extending the ERC20 standard contract (picture above).
I used the following command to deploy the contract:

`starkli deploy --account ~/.starkli-wallets/deployer/account.json --keystore ~/.starkli-wallets/deployer/keystore.json --watch 0x0751012e95eb15318a7036d935c552bf19c526a429c90dc7d8aa611f0e530cc4 u256:100 0x052E6AD8187767eF41F2F3bc225D33d31B37DD9BBEE7B628F4b6b16b90D293EC 
`
Expected Behavior:
The contract should deploy successfully.

Actual Behavior:
I received the following error:

Error: code=ValidationFailure, message="Execution was reverted; failure reason: [0x496e70757420746f6f206c6f6e6720666f7220617267756d656e7473]."

Any assistance or guidance on this issue would be greatly appreciated.

Thank you!

**Comment by mbzdg** [comment]
Try bravos wallet, I got same error "?Input too long for arguments", and changed to bravos, it built.

**Comment by henryf10h** [comment]
Thanks for the help @mbzdg. 

I forgot to re-fetch my argentX's account file after I upgraded it.
