### ISSUE TITLE
Update Starknet book references

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#788]
For example the ones in the [Security considerations section](https://book.starknet.io/chapter_2/security_considerations.html)

**Comment by Nonnyjoe** [comment]
To be clear this issue is about updating the reference contracts in Starknet book  to the latest Cairo version right?
If yes, then I'll like to handle this task.

**Comment by martriay** [comment]
Yes, any OpenZeppelin code and links to our docs like

> You can create your own custom solution or use existing templates like those provided by OpenZeppelin

**Comment by Nonnyjoe** [comment]
Okay that's fine.
I'll check out the Starknet book repo, then reach out to the person in-charge, also possibly create an issue ASAP.

**Comment by omarespejel** [comment]
Thanks, @martriay. It seems you're looking at an older version of the Book. The current version is at book.starknet.io and we no longer have that chapter. We'll investigate why the previous version is still visible.

**Comment by martriay** [comment]
@omarespejel should we still have an access control dedicated section with examples?

**Comment by omarespejel** [comment]
@martriay, I see the value in including it. However, we're aiming to keep Cairo-related content in the Cairo Book, specifically in the [access control section](https://book.cairo-lang.org/ch99-03-security-considerations.html?highlight=access%20control#access-control). In your view, should we add more examples to the current version?

**Comment by martriay** [comment]
Access Control is 100% Starknet, there's no sender notion in Cairo

**Comment by omarespejel** [comment]
Thank you @martriay, this is invaluable. We will open an issue in the Starknet Book to get contributors to write the Access Control section.

**Comment by Nonnyjoe** [comment]
@omarespejel could you please assign that to me, I'll like to work on that

**Comment by martriay** [comment]
I'll close this issue since there's not outdated references to fix anymore. Looking forward to the new content!

**Comment by omarespejel** [comment]
Thank you, @martriay and @Nonnyjoe, for bringing this important issue to our vision. We've responded by adding a chapter on it: [Security Considerations Chapter](https://book.starknet.io/ch02-14-security-considerations.html), with credit to author @devnet0x.

We welcome any further insights or feedback!
