### ISSUE TITLE
Migrate to the `2023_11` edition

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#856]
This edition is about reducing the default scope of corelib, requiring more explicit imports.

**Comment by TAdev0** [comment]
@ericnordelo  @martriay  may i be assigned to this issue? I think the migration should now use `2023_11` edition, which includes the same 2023_10 + pub / pub(crate) keywords from 2.5.0

**Comment by TAdev0** [comment]
@martriay  thanks for the quick answer!
