### ISSUE TITLE
Error: error from the program registry

### ISSUE THREAD

**Issue by wzny-drj** [OpenZeppelin/cairo-contracts#859]
#1

<img width="635" alt="test1" src="https://github.com/OpenZeppelin/cairo-contracts/assets/57926399/af998e26-6b46-4090-8fd2-55655b483e8e">

**Comment by martriay** [comment]
Sorry, this issue has no explanation or context, we cannot help you since we don't know what's the contract you're working with. Feel free to open a new issue with a problem statement and clear reproduction steps.

**Comment by shashwat0309** [comment]
This error generally occurs when we try to declare contract using incorrect Starkli version, so you need to check Cairo & Starkli versions compatibility in this case you can try using `starkliup` and then again try to declare contracts
