### ISSUE TITLE
Update ERC20 Contract Nomenclature to Match Standard

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/cairo-contracts#86]
# Update ERC20 Contract Nomenclature to Match Standard 

## ERC20 Method Names

All `snake_case` functions should be changed to `camelCase` in order to match the standard put forth in [EIP20](https://eips.ethereum.org/EIPS/eip-20). See the [ERC20 function naming discussion](https://github.com/OpenZeppelin/cairo-contracts/discussions/34). 

## Update ERC20 Parameters and Return Value Names

The parameters and return value names should mirror those set in EIP20. For example:
```
@view
func balance_of{
    ...
    }(account: felt) -> (res: Uint256):
    ...
end
```

`res` should be changed to `balance`.

**Comment by martriay** [comment]
Let's keep `account` there so it's consistent with [the solidity implementation](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol#L101).

**Comment by andrew-fleming** [comment]
Ah okay, thank you.
