### ISSUE TITLE
Problems with Cairo and Scarb 2.5.0

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#877]
We should update the library to support Cairo 2.5.0.

### Context
Many users are experiencing issues when trying to use our v0.8.1 release with Cairo and Scarb v2.5.0.

The problem is that v2.5.0 introduced breaking API changes, so it should have been v3.0.0 instead. This is leaking downstream to Scarb where the compatibility check fails to detect this version update as a breaking one, resulting in this error. **You should not be allowed to use Contracts for Cairo <=0.8.1 with Cairo 2.5.0**.

**Comment by vivekmishra9631** [comment]
Heyy, I am getting this error now. How do I resolve. 
![image](https://github.com/OpenZeppelin/cairo-contracts/assets/114434748/08c1a989-32a2-4084-8663-0917a307b226)
