### ISSUE TITLE
ERC721: Questions and thinking about Felt252 for Trait for URI for Token URI and Contract base URI. 

### ISSUE THREAD

**Issue by MSghais** [OpenZeppelin/cairo-contracts#886]
**🧐 Motivation**

I'm starting to check the repo on Cairo Open Zeppelin. 
New to Cairo, so I'm trying to build a few things.

1. Rising question: 

Thinking about standards for the NFT token_uri and contract_uri, for the NFT marketplace, etc.

We can't use Ipfs hash for token_uri with Felt252. 
How we can fix it or use it in another way?

I've seen the use of Array<felt252> too, but I'm thinking also about implementing it with Bytes of: https://github.com/keep-starknet-strange/alexandria

Implement a way to use Ipfs Hash with Array<felt>, Bytes also Open Zeppelin?

What do you think @martriay?

**Comment by martriay** [comment]
Briefly addressed [in our docs](https://docs.openzeppelin.com/contracts-cairo/0.8.1/erc721#storing_erc721_uris), tl;dr we're currently working on [`ByteArray` support](https://github.com/OpenZeppelin/cairo-contracts/pull/857) which will be the preferred format going forward.
