### ISSUE TITLE
Add docs for ERC721Receiver component

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/cairo-contracts#913]
Right now only its interface is documented

![image](https://github.com/OpenZeppelin/cairo-contracts/assets/1703831/df3d1055-9eb4-45c9-8fd7-12e32de8ce49)

**Comment by ericnordelo** [comment]
We also have [this](https://docs.openzeppelin.com/contracts-cairo/0.9.0/erc721#receiving_tokens) in the ERC721 doc.

**Comment by martriay** [comment]
@ericnordelo what do you mean? should we do anything with it?

**Comment by ericnordelo** [comment]
Just pointing up that not just the interface is documented, but realized the issue is probably referring to the API Reference section.
