### ISSUE TITLE
Remove nonce from execute function's arguments

### ISSUE THREAD

**Issue by merkle-groot** [OpenZeppelin/cairo-contracts#92]
The current implementation of the Account contract requires the nonce as argument even though it's not used in the function. In fact the current nonce is read from a storage variable *current_nonce*, hence there's no need to have nonce as a function parameter.

**Comment by martriay** [comment]
That's to comply with [the standard interface](https://github.com/OpenZeppelin/cairo-contracts/discussions/41). Other Account implementations might have different nonce strategies, so it's required even though this particular implementation does not make use of it.
