### ISSUE TITLE
Pass library version to Wizard in docs

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/cairo-contracts#928]
**🧐 Motivation**
Wizard is only compatible with specific versions of this library, and this is shown on Wizard as a semantic version string.

When accessing Wizard from the documentation site, if the selected version of the library is not compatible with Wizard, we should show an appropriate error message.

**📝 Details**
For each branch where Wizard is available, pass through a `version` parameter of the current library version when embedding Wizard.  This will cause Wizard to render an error page if that version is not supported.

Related to: https://github.com/OpenZeppelin/contracts-wizard/pull/335

**Comment by ericglau** [comment]
This was addressed in the main and release branches, but the changes for the release branches do not appear in the docs site because the docs site is using version tags due to https://github.com/OpenZeppelin/cairo-contracts/issues/869.

@martriay Would it make sense to migrate the version tags again for these branche, similar to https://github.com/OpenZeppelin/cairo-contracts/issues/869#issuecomment-1935230841 ?

**Comment by martriay** [comment]
We've learned the hard way it could be problematic to re-tag versions. We need to re-release releases because they're automatically drafted when a tag is deleted. We should probably define a process for re tagging and document it.

**Comment by martriay** [comment]
Well apparently the releases are only drafted if the tag is deleted, but I just force pushed new tags and it worked perfectly.

**Comment by ericglau** [comment]
Thanks! This is resolved now.
