### ISSUE TITLE
Use MixinImpls in documentation examples

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/cairo-contracts#948]
This issue aims to reduce the examples' code size by consistently using mixins instead of separate embeddable implementations.

**Comment by martriay** [comment]
which ones specifically?

**Comment by ericnordelo** [comment]
Like these:
https://docs.openzeppelin.com/contracts-cairo/0.10.0/erc721#usage
https://docs.openzeppelin.com/contracts-cairo/0.10.0/erc20#usage
