### ISSUE TITLE
Add financial systems

### ISSUE THREAD

**Issue by zpano** [OpenZeppelin/cairo-contracts#973]
**🧐 Motivation**
add cairo's financial systems

**📝 Details**
Ref: https://github.com/OpenZeppelin/openzeppelin-contracts/tree/master/contracts/finance

rewrite VestingWallet && VestingWalletCliff

**Comment by andrew-fleming** [comment]
@zpano thanks for posting the issue!

This is definitely something we want to add. We plan on tackling it in a forthcoming milestone: https://github.com/orgs/OpenZeppelin/projects/29/views/11

**Comment by zpano** [comment]
@andrew-fleming How can i distrubite code for this feature?

**Comment by ericnordelo** [comment]
Completed as part of #1116
