### ISSUE TITLE
Incorrect interface examples in docs

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/cairo-contracts#985]
In the docsite's ["Standard traits"](https://docs.openzeppelin.com/contracts-cairo/0.12.0/interfaces#standard_traits) and ["ABI traits"](https://docs.openzeppelin.com/contracts-cairo/0.12.0/interfaces#abi_traits) sections, the example interfaces in the code blocks are old. They should reflect the current `IERC20` and `ERC20ABI` interfaces defined in [erc20/interface.cairo](https://github.com/OpenZeppelin/cairo-contracts/blob/release-v0.12.0/src/token/erc20/interface.cairo)

**Comment by murluki** [comment]
Can you assign it to me, please?

**Comment by andrew-fleming** [comment]
Sorry, @murluki! We already have an open PR for this
